
- name: Install kubectl
  # https://kubernetes.io/docs/tasks/tools/install-kubectl/
  shell: |
      KUBE_VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
      wget -O /tmp/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl
      chmod +x /tmp/kubectl
      sudo mv /tmp/kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/kubectl

- name: Create .kube directory
  file:
    path: "/home/{{ user }}/.kube"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"   

- name: Check if Windows kube config exists
  stat:
    path: "{{ user_windows_path }}/.kube/config"
  register: windows_kube_config
  when: is_wsl

- name: Create a symbolic link to Windows kube config
  file:
    src: "{{ user_windows_path }}/.kube/config"
    dest: "/home/{{ user }}/.kube/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  when: 
    - is_wsl
    - windows_kube_config.stat.exists

- name: Install Kind
  get_url:
    url: https://kind.sigs.k8s.io/dl/v{{ kind_version }}/kind-linux-amd64
    dest: /usr/local/bin/kind
    mode: a+x

- name: Install Helm
  # https://helm.sh/docs/intro/install/
  shell: |
      cd /tmp
      wget https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz
      tar -zxvf helm-v3.7.0-linux-amd64.tar.gz
      mv linux-amd64/helm /usr/local/bin/helm
      helm repo add stable https://charts.helm.sh/stable
  args:
    creates: /usr/local/bin/helm

- name: Install kubectx and kubens
  shell: |
      curl -O https://raw.githubusercontent.com/ahmetb/kubectx/master/kubectx
      chmod +x kubectx
      mv kubectx /usr/local/bin/
      curl -O https://raw.githubusercontent.com/ahmetb/kubectx/master/kubens
      chmod +x kubens
      mv kubens /usr/local/bin/
  args:
    creates: /usr/local/bin/kubectx
  
- name: Install K9s
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/v0.19.6/k9s_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: True

- name: Download Octant
  get_url: 
    url: https://github.com/vmware-tanzu/octant/releases/download/v0.12.1/octant_0.12.1_Linux-64bit.deb
    dest: /tmp/octant.deb
  register: octant_download
  failed_when: false

- name: Install Octant
  apt:
    deb: /tmp/octant.deb
  when: 
    - octant_download is succeeded
    - octant_download.status_code is defined
    - octant_download.status_code == 200


- name: Install Linkerd
  shell: |
      curl -sL https://run.linkerd.io/install | sh
  args:    
    creates: "/home/{{ user }}/.linkerd2/bin"


